# clusters/my-cluster/my-nginx-chart-source.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-nginx
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/gprashant2/fluxcd-gitops-repo
  ref:
    branch: main
